# Generated by Django 3.2.16 on 2023-06-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230529_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('id',), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
